version: "3"
services:
  app_tests:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/user/app:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3001:3000
    networks:
        - test
    depends_on:
        - postgres
        - redis
  redis:
    image: 'redis:alpine'
    ports:
        - '6390:6379'
    networks:
        - test

  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tests
    networks:
        - test
networks:
    test:
        driver: bridge