version: "3"
services:
  app_moovin:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/user/app:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3001:3000
